[build]
builder = "nixpacks"
watchPatterns = ["src/**/*.py", "requirements.txt"]

[deploy]
startCommand = "cd src && python manage.py migrate && gunicorn config.wsgi:application"
healthcheckPath = "/api/health/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
python_version = "3.11.7"