# Generated by Django 5.1.7 on 2025-03-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_level",
                    models.CharField(
                        choices=[
                            ("A1", "Básico Iniciante"),
                            ("A2", "Básico"),
                            ("B1", "Intermediário Iniciante"),
                            ("B2", "Intermediário"),
                            ("C1", "Avançado Iniciante"),
                            ("C2", "Avançado"),
                        ],
                        default="A1",
                        max_length=2,
                    ),
                ),
                ("total_cards", models.IntegerField(default=0)),
                ("mastered_cards", models.IntegerField(default=0)),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("accuracy_rate", models.FloatField(default=0)),
                ("average_response_time", models.FloatField(default=0)),
                ("cards_per_day", models.IntegerField(default=0)),
                ("time_spent", models.IntegerField(default=0)),
                ("last_study_date", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "user progress",
                "verbose_name_plural": "user progress",
            },
        ),
    ]
