# Generated by Django 5.1.7 on 2025-03-26 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprogress",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "progresso do usuário",
                "verbose_name_plural": "progressos dos usuários",
            },
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="accuracy_rate",
            field=models.FloatField(default=0, verbose_name="taxa de acerto"),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="average_response_time",
            field=models.FloatField(default=0, verbose_name="tempo médio de resposta"),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="cards_per_day",
            field=models.IntegerField(default=0, verbose_name="cartões por dia"),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="current_level",
            field=models.CharField(
                choices=[
                    ("A1", "Iniciante"),
                    ("A2", "Básico"),
                    ("B1", "Intermediário"),
                    ("B2", "Intermediário Superior"),
                    ("C1", "Avançado"),
                    ("C2", "Proficiente"),
                ],
                default="A1",
                max_length=2,
                verbose_name="nível atual",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="current_streak",
            field=models.IntegerField(default=0, verbose_name="sequência atual"),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="last_study_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="última data de estudo"),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="longest_streak",
            field=models.IntegerField(default=0, verbose_name="maior sequência"),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="mastered_cards",
            field=models.IntegerField(default=0, verbose_name="cartões dominados"),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="time_spent",
            field=models.IntegerField(
                default=0,
                help_text="Tempo total gasto estudando em minutos",
                verbose_name="tempo gasto",
            ),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="total_cards",
            field=models.IntegerField(default=0, verbose_name="total de cartões"),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
        ),
        migrations.AlterField(
            model_name="userprogress",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuário",
            ),
        ),
    ]
