# Generated by Django 5.1.7 on 2025-03-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("streak", "Streak"),
                            ("cards", "Cards"),
                            ("accuracy", "Accuracy"),
                            ("level", "Level"),
                            ("time", "Time"),
                        ],
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                ("icon", models.CharField(default="trophy", max_length=50)),
                ("points", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-unlocked_at"],
            },
        ),
        migrations.CreateModel(
            name="AchievementDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("streak", "Streak"),
                            ("cards", "Cards"),
                            ("accuracy", "Accuracy"),
                            ("level", "Level"),
                            ("time", "Time"),
                        ],
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="trophy", max_length=50)),
                ("points", models.IntegerField(default=0)),
                ("requirement_value", models.IntegerField()),
                ("requirement_type", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["type", "requirement_value"],
            },
        ),
    ]
