# Generated by Django 5.1.7 on 2025-03-26 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("achievements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(fields=["user"], name="achievement_user_id_777a3e_idx"),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(fields=["type"], name="achievement_type_9eafce_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="achievement",
            unique_together={("user", "type", "name")},
        ),
    ]
