# Generated by Django 5.1.7 on 2025-03-26 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front", models.TextField()),
                ("back", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "Básico Iniciante"),
                            ("A2", "Básico"),
                            ("B1", "Intermediário Iniciante"),
                            ("B2", "Intermediário"),
                            ("C1", "Avançado Iniciante"),
                            ("C2", "Avançado"),
                        ],
                        max_length=2,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                (
                    "tags",
                    models.CharField(
                        help_text="Tags separadas por vírgula", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["level"], name="flashcards__level_33deae_idx"),
                    models.Index(
                        fields=["category"], name="flashcards__categor_25fa19_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FlashcardProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correct_attempts", models.IntegerField(default=0)),
                ("incorrect_attempts", models.IntegerField(default=0)),
                ("average_response_time", models.FloatField(default=0)),
                ("last_reviewed", models.DateTimeField(null=True)),
                ("next_review_date", models.DateTimeField(null=True)),
                ("ease_factor", models.FloatField(default=2.5)),
                ("interval", models.IntegerField(default=1)),
                ("streak", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flashcards.flashcard",
                    ),
                ),
            ],
            options={
                "ordering": ["next_review_date"],
            },
        ),
    ]
