# Generated by Django 5.1.7 on 2025-03-26 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flashcards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcardprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="flashcardprogress",
            index=models.Index(fields=["user"], name="flashcards__user_id_c41458_idx"),
        ),
        migrations.AddIndex(
            model_name="flashcardprogress",
            index=models.Index(
                fields=["flashcard"], name="flashcards__flashca_bbcf98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flashcardprogress",
            index=models.Index(
                fields=["next_review_date"], name="flashcards__next_re_65721e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="flashcardprogress",
            unique_together={("user", "flashcard")},
        ),
    ]
