groups:
  - name: django
    rules:
      - alert: HighRequestLatency
        expr: http_request_latency_seconds{quantile="0.9"} > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          title: High request latency on {{ $labels.instance }}
          description: "90% of requests are taking more than 1s to complete."

      - alert: HighErrorRate
        expr: rate(django_http_responses_total_by_status_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          title: High error rate on {{ $labels.instance }}
          description: "Error rate is above 10% in the last 5 minutes."

  - name: node
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          title: High CPU usage on {{ $labels.instance }}
          description: "CPU usage is above 80% for 5 minutes."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          title: High memory usage on {{ $labels.instance }}
          description: "Memory usage is above 85% for 5 minutes."

      - alert: LowDiskSpace
        expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          title: Low disk space on {{ $labels.instance }}
          description: "Disk usage is above 85% for 5 minutes."

  - name: postgres
    rules:
      - alert: PostgresqlDown
        expr: pg_up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          title: PostgreSQL is down on {{ $labels.instance }}
          description: "PostgreSQL instance has been down for more than 5 minutes."

      - alert: PostgresqlHighConnections
        expr: sum by (instance) (pg_stat_activity_count) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          title: High number of PostgreSQL connections on {{ $labels.instance }}
          description: "PostgreSQL instance has more than 100 active connections."

  - name: redis
    rules:
      - alert: RedisDown
        expr: redis_up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          title: Redis is down on {{ $labels.instance }}
          description: "Redis instance has been down for more than 5 minutes."

      - alert: RedisOutOfMemory
        expr: redis_memory_used_bytes / redis_total_system_memory_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          title: Redis memory usage high on {{ $labels.instance }}
          description: "Redis memory usage is above 85% for 5 minutes." 